[package]
name = "rsm-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "=1.18.26"
spl-token = "=4.0.0"
borsh = "=0.10.4"
thiserror = "=1.0.69"

[dev-dependencies]
solana-program-test = "=1.18.26"
solana-sdk = "=1.18.26"
